CREATE TABLE collectables (
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users not null,
 description text,
 type text,
 grading text,
 inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- alter table users enable row level security;

-- create policy "Individuals can create workouts." on workouts for
--    insert with check (auth.uid() = user_id);

-- create policy "Individuals can update their own workouts." on workouts for
--    update using (auth.uid() = user_id);

-- create policy "Individuals can delete their own workouts." on workouts for
--    delete using (auth.uid() = user_id);

-- create policy "Workouts are public." on workouts for
--    select using (true);