// @ts-nocheck
// /pages/index.js
import Head from 'next/head';
import Link from 'next/link';
import React, { useEffect, useState } from 'react';
import { supabase } from '../utils/supabase';

export default function Home({ session }) {
	const [workouts, setWorkouts] = useState([]);
	const [loading, setLoading] = useState(true);

	// useEffect(() => {
	// 	fetchWorkouts();
	// }, []);

	const fetchWorkouts = async () => {
		const user = supabase.auth.getUser();
		try {
			setLoading(true);
			const { data, error } = await supabase.from('workouts').select('*');
			// .eq('user_id', user?.id);

			if (error) throw error;
			setWorkouts(data);
		} catch (error) {
			alert(error.message);
		} finally {
			setLoading(false);
		}
	};

	if (loading) {
		return <div>Fetching Workouts...</div>;
	}
	return (
		<div>
			<Head>
				<title>Nextjs x Supabase</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div>
				{!session?.user ? (
					<div>
						<p>
							Welcome to Adrenargy. Kindly log in to your account or sign in for
							a demo
						</p>
					</div>
				) : (
					<div>
						<p>
							Hello <span>{session.user.email}</span>, Welcome to your dashboard
						</p>
						{workouts?.length === 0 ? (
							<div className={styles.noWorkout}>
								<p>You have no workouts yet</p>
								<Link href='/create'>
									<button> Create a New Workout</button>
								</Link>
							</div>
						) : (
							<div>
								<p>Here are your workouts</p>
							</div>
						)}
					</div>
				)}
			</div>
		</div>
	);
}
